# ============================================================
# ADAPTIVE HEALTH MANAGEMENT PLATFORM
# seed_recipes.py — Seed all 205 recipes + health conditions
# Run once: python seed_recipes.py
# ============================================================

from app import app
from models import db, Recipe, HealthCondition, seed_health_conditions


# ============================================================
# COMPLETE 205 RECIPES DATASET
# ============================================================

recipes_data = [

# ── BREAKFAST (30) ──────────────────────────────────────────
{"name":"Oats Banana Porridge","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":280,"protein":10,"carbs":42,"fats":5,"fiber":8,"sodium":45,"potassium":420,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Banana,Low Fat Milk,Cinnamon","health_benefits":"High fiber and potassium from banana helps lower BP. Oats provide beta-glucan which reduces cholesterol."},
{"name":"Oats Banana Smoothie","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":280,"protein":12,"carbs":40,"fats":6,"fiber":8,"sodium":60,"potassium":400,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Banana,Low Fat Milk,Chia Seeds","health_benefits":"Rich in omega-3 from chia seeds. Potassium from banana supports healthy BP."},
{"name":"Ragi Porridge","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":260,"protein":8,"carbs":38,"fats":4,"fiber":7,"sodium":30,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ragi Flour,Low Fat Milk,Banana","health_benefits":"Ragi is rich in calcium and fiber. Low glycemic index helps control blood sugar."},
{"name":"Ragi Dosa","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":270,"protein":8,"carbs":40,"fats":6,"fiber":7,"sodium":90,"potassium":280,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ragi Flour,Onion,Green Chilli","health_benefits":"Calcium-rich ragi supports bone health. Low sodium preparation keeps BP stable."},
{"name":"Idli Sambar","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":290,"protein":10,"carbs":42,"fats":5,"fiber":6,"sodium":180,"potassium":350,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rice Batter,Urad Dal,Sambar Vegetables","health_benefits":"Fermented food improves gut health. Low fat, high protein breakfast for sustained energy."},
{"name":"Vegetable Upma","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":320,"protein":9,"carbs":45,"fats":10,"fiber":5,"sodium":120,"potassium":290,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rava,Carrot,Beans,Onion,Mustard Seeds","health_benefits":"Vegetables add potassium and fiber. Mustard seeds contain heart-protective compounds."},
{"name":"Moong Dal Chilla","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":300,"protein":15,"carbs":28,"fats":9,"fiber":6,"sodium":80,"potassium":340,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moong Dal,Onion,Tomato,Green Chilli","health_benefits":"High protein keeps you full. Moong dal is easy to digest and low in fat."},
{"name":"Sprouts Salad Breakfast","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":210,"protein":14,"carbs":22,"fats":5,"fiber":8,"sodium":40,"potassium":460,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mixed Sprouts,Onion,Tomato,Lemon","health_benefits":"Sprouts are rich in potassium and plant protein. Raw foods retain maximum nutrients for heart health."},
{"name":"Poha","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":250,"protein":6,"carbs":38,"fats":7,"fiber":4,"sodium":80,"potassium":200,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Poha,Peanuts,Onion,Mustard Seeds,Turmeric","health_benefits":"Iron-rich breakfast. Low fat when made with minimal oil. Turmeric provides anti-inflammatory benefit."},
{"name":"Boiled Eggs With Vegetables","category":"Breakfast","meal_type":"Breakfast","is_veg":False,"calories":200,"protein":14,"carbs":8,"fats":10,"fiber":3,"sodium":130,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Eggs,Cucumber,Tomato,Carrot","health_benefits":"High protein breakfast stabilizes blood sugar. Vegetables add potassium to offset sodium."},
{"name":"Egg White Omelette","category":"Breakfast","meal_type":"Breakfast","is_veg":False,"calories":180,"protein":18,"carbs":4,"fats":6,"fiber":1,"sodium":110,"potassium":280,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Egg Whites,Onion,Tomato,Spinach","health_benefits":"Very high protein, low fat. Spinach adds iron and folate. Excellent for weight loss and muscle maintenance."},
{"name":"Whole Wheat Roti With Sabzi","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":340,"protein":10,"carbs":48,"fats":9,"fiber":6,"sodium":90,"potassium":320,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Whole Wheat Atta,Mixed Vegetables,Mustard Oil","health_benefits":"Whole wheat provides slow-release energy. Vegetables add micronutrients essential for BP control."},
{"name":"Bajra Roti With Curd","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":310,"protein":9,"carbs":44,"fats":6,"fiber":8,"sodium":60,"potassium":290,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bajra Flour,Low Fat Curd","health_benefits":"Bajra is rich in magnesium which relaxes blood vessels. Curd provides probiotics for gut health."},
{"name":"Jowar Roti With Dal","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":320,"protein":11,"carbs":46,"fats":5,"fiber":7,"sodium":70,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Jowar Flour,Moong Dal","health_benefits":"Jowar is gluten-free and high in iron. High fiber content helps manage BP and cholesterol."},
{"name":"Besan Chilla","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":290,"protein":14,"carbs":26,"fats":10,"fiber":5,"sodium":95,"potassium":300,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Besan,Onion,Tomato,Spinach","health_benefits":"Chickpea flour is rich in plant protein and fiber. Low glycemic helps stabilize blood sugar."},
{"name":"Avocado Toast","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":300,"protein":8,"carbs":28,"fats":17,"fiber":9,"sodium":110,"potassium":480,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Whole Wheat Bread,Avocado,Lemon","health_benefits":"Avocado is rich in potassium and healthy fats. High potassium directly counters sodium effects on BP."},
{"name":"Paneer Scramble","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":310,"protein":18,"carbs":8,"fats":20,"fiber":2,"sodium":120,"potassium":220,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Low Fat Paneer,Onion,Tomato,Turmeric","health_benefits":"High protein keeps you full for hours. Turmeric provides anti-inflammatory curcumin."},
{"name":"Chia Seed Pudding","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":240,"protein":10,"carbs":22,"fats":12,"fiber":10,"sodium":55,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chia Seeds,Low Fat Milk,Banana","health_benefits":"Chia seeds are highest plant source of omega-3. Fiber-rich for gut health and blood sugar control."},
{"name":"Masala Oats","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":300,"protein":10,"carbs":40,"fats":8,"fiber":6,"sodium":100,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Vegetables,Cumin,Turmeric","health_benefits":"Beta-glucan in oats lowers cholesterol. Anti-inflammatory spices support heart health."},
{"name":"Quinoa Breakfast Bowl","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":310,"protein":12,"carbs":38,"fats":9,"fiber":7,"sodium":60,"potassium":390,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Quinoa,Banana,Almonds,Low Fat Milk","health_benefits":"Complete protein from quinoa. High magnesium content relaxes blood vessels."},
{"name":"Flaxseed Oats Porridge","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":290,"protein":11,"carbs":38,"fats":9,"fiber":9,"sodium":50,"potassium":370,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Ground Flaxseeds,Low Fat Milk,Banana","health_benefits":"Flaxseeds are proven to lower BP. Combined with oats fiber provides powerful cardiovascular protection."},
{"name":"Methi Paratha Minimal Oil","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":280,"protein":8,"carbs":40,"fats":8,"fiber":5,"sodium":85,"potassium":270,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Whole Wheat Atta,Fenugreek Leaves,Minimal Oil","health_benefits":"Fenugreek helps lower blood sugar. Whole wheat provides sustained energy without BP spikes."},
{"name":"Millet Upma","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":300,"protein":8,"carbs":42,"fats":8,"fiber":6,"sodium":80,"potassium":280,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Foxtail Millet,Vegetables,Mustard Seeds","health_benefits":"Millets are rich in magnesium. Low glycemic index prevents blood sugar spikes."},
{"name":"Protein Oats Bowl","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":290,"protein":20,"carbs":30,"fats":8,"fiber":7,"sodium":80,"potassium":340,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Whey Protein,Banana","health_benefits":"High protein promotes satiety. Potassium from banana supports healthy blood pressure."},
{"name":"Tofu Scramble","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":250,"protein":18,"carbs":10,"fats":14,"fiber":3,"sodium":100,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tofu,Onion,Tomato,Turmeric,Spinach","health_benefits":"Plant-based protein. Tofu contains isoflavones which improve arterial flexibility."},
{"name":"Pesarattu","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":280,"protein":14,"carbs":32,"fats":8,"fiber":6,"sodium":75,"potassium":320,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Green Moong,Ginger,Onion","health_benefits":"Whole moong is high in protein and folate. Ginger improves circulation and reduces arterial stiffness."},
{"name":"Uttapam Low Oil","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":310,"protein":9,"carbs":44,"fats":8,"fiber":5,"sodium":110,"potassium":290,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rice Batter,Onion,Tomato,Capsicum","health_benefits":"Fermented rice batter improves gut microbiome. Vegetables add antioxidants and potassium."},
{"name":"Cornflakes With Low Fat Milk","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":240,"protein":9,"carbs":38,"fats":4,"fiber":2,"sodium":140,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cornflakes,Low Fat Milk","health_benefits":"Quick energy source. Low fat milk provides calcium for vessel function."},
{"name":"Sabudana Khichdi Low Oil","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":330,"protein":6,"carbs":52,"fats":8,"fiber":3,"sodium":60,"potassium":250,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Sabudana,Peanuts,Potato","health_benefits":"Easy to digest. Peanuts provide heart-healthy fats and plant protein."},
{"name":"Soaked Almond Walnut Bowl","category":"Breakfast","meal_type":"Breakfast","is_veg":True,"calories":220,"protein":7,"carbs":10,"fats":18,"fiber":4,"sodium":5,"potassium":320,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Soaked Almonds,Walnuts,Banana","health_benefits":"Walnuts are richest plant source of omega-3. Almonds provide magnesium for BP control."},

# ── LUNCH (30) ──────────────────────────────────────────────
{"name":"Brown Rice Dal Sabzi","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":480,"protein":18,"carbs":70,"fats":10,"fiber":12,"sodium":160,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Brown Rice,Toor Dal,Seasonal Vegetable","health_benefits":"Complete nutrition. Brown rice and dal together form complete protein. High potassium from vegetables."},
{"name":"Dal Khichdi","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":430,"protein":15,"carbs":58,"fats":10,"fiber":8,"sodium":140,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rice,Moong Dal,Vegetables,Turmeric","health_benefits":"One-pot meal with complete nutrition. Turmeric provides curcumin anti-inflammatory benefit."},
{"name":"Rajma Rice","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":530,"protein":17,"carbs":72,"fats":12,"fiber":11,"sodium":180,"potassium":580,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rajma,Brown Rice,Onion,Tomato","health_benefits":"Rajma is very high in potassium and fiber. Excellent for BP management and weight loss."},
{"name":"Palak Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":420,"protein":16,"carbs":52,"fats":10,"fiber":9,"sodium":130,"potassium":510,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Spinach,Moong Dal,Whole Wheat Roti","health_benefits":"Spinach is rich in folate and potassium. Combined with dal provides excellent plant protein."},
{"name":"Grilled Fish With Salad","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":360,"protein":32,"carbs":12,"fats":16,"fiber":5,"sodium":190,"potassium":620,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mackerel,Lemon,Cucumber,Tomato","health_benefits":"Mackerel is richest source of omega-3. Anti-inflammatory fats directly lower BP. High potassium."},
{"name":"Soya Chunk Curry Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":430,"protein":28,"carbs":32,"fats":14,"fiber":7,"sodium":170,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Soya Chunks,Onion,Tomato,Whole Wheat Roti","health_benefits":"Soya isoflavones improve arterial health. Highest plant protein source after legumes."},
{"name":"Quinoa Vegetable Bowl","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":410,"protein":16,"carbs":50,"fats":12,"fiber":9,"sodium":110,"potassium":470,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Quinoa,Broccoli,Beans,Capsicum","health_benefits":"Complete protein with all essential amino acids. High magnesium content relaxes blood vessels."},
{"name":"Chana Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":440,"protein":18,"carbs":56,"fats":10,"fiber":10,"sodium":130,"potassium":450,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chana Dal,Whole Wheat Roti,Onion,Tomato","health_benefits":"Chickpea dal is high in folate and fiber. Helps reduce LDL cholesterol."},
{"name":"Mushroom Sabzi Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":380,"protein":13,"carbs":40,"fats":14,"fiber":6,"sodium":130,"potassium":440,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mushroom,Onion,Tomato,Whole Wheat Roti","health_benefits":"Mushrooms are rich in potassium and B vitamins. Support immune system and heart health."},
{"name":"Chicken Breast Brown Rice","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":480,"protein":38,"carbs":42,"fats":12,"fiber":4,"sodium":200,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken Breast,Brown Rice,Vegetables","health_benefits":"Lean protein for muscle maintenance. Brown rice provides slow energy. High potassium from vegetables."},
{"name":"Masoor Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":400,"protein":16,"carbs":50,"fats":9,"fiber":9,"sodium":120,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Masoor Dal,Whole Wheat Roti,Garlic,Onion","health_benefits":"Red lentils are rich in iron and folate. Garlic contains allicin which opens blood vessels."},
{"name":"Lauki Sabzi Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":350,"protein":12,"carbs":46,"fats":8,"fiber":8,"sodium":100,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bottle Gourd,Dal,Whole Wheat Roti","health_benefits":"Lauki is 96% water and very low calorie. Its juice is known to actively lower BP."},
{"name":"Fish Curry Brown Rice","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":520,"protein":30,"carbs":48,"fats":18,"fiber":4,"sodium":220,"potassium":540,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Rohu Fish,Brown Rice,Onion,Tomato","health_benefits":"Rohu is high in omega-3 and protein. Supports cardiovascular health."},
{"name":"Karela Sabzi Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":310,"protein":10,"carbs":38,"fats":10,"fiber":7,"sodium":90,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bitter Gourd,Dal,Whole Wheat Roti","health_benefits":"Karela is proven to lower blood sugar and supports BP management. One of the best vegetables for diabetics."},
{"name":"Turai Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":340,"protein":12,"carbs":44,"fats":8,"fiber":8,"sodium":95,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ridge Gourd,Dal,Whole Wheat Roti","health_benefits":"Ridge gourd is high in water and low calorie. Excellent for weight management."},
{"name":"Drumstick Sambar Rice","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":420,"protein":14,"carbs":60,"fats":10,"fiber":9,"sodium":170,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Drumstick,Toor Dal,Brown Rice","health_benefits":"Drumstick (moringa) is rich in calcium and iron. Very high antioxidant content."},
{"name":"Tofu Vegetable Stir Fry","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":340,"protein":18,"carbs":24,"fats":16,"fiber":6,"sodium":130,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tofu,Broccoli,Capsicum,Beans","health_benefits":"Tofu isoflavones improve arterial flexibility. Broccoli provides sulforaphane which protects heart."},
{"name":"Palak Paneer Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":420,"protein":20,"carbs":30,"fats":22,"fiber":6,"sodium":170,"potassium":490,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Spinach,Low Fat Paneer,Whole Wheat Roti","health_benefits":"Iron from spinach and calcium from paneer. High potassium content supports BP reduction."},
{"name":"Moringa Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":380,"protein":14,"carbs":48,"fats":9,"fiber":8,"sodium":110,"potassium":480,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Drumstick Leaves,Dal,Whole Wheat Roti","health_benefits":"Moringa is most nutrient-dense food. Contains compounds that directly lower BP."},
{"name":"Barley Vegetable Soup Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":360,"protein":12,"carbs":50,"fats":8,"fiber":10,"sodium":130,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Barley,Mixed Vegetables,Whole Wheat Roti","health_benefits":"Beta-glucan in barley lowers cholesterol. High fiber content keeps BP stable."},
{"name":"Sprouts Dal Rice","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":400,"protein":18,"carbs":54,"fats":8,"fiber":10,"sodium":100,"potassium":460,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mixed Sprouts,Dal,Brown Rice","health_benefits":"Sprouted legumes have higher bioavailable nutrients. High potassium content ideal for BP patients."},
{"name":"Salmon With Vegetables","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":450,"protein":34,"carbs":20,"fats":24,"fiber":5,"sodium":200,"potassium":650,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Salmon,Broccoli,Carrot,Lemon","health_benefits":"Salmon is highest source of omega-3 EPA and DHA. Proven to reduce systolic BP by 4-5 mmHg."},
{"name":"Egg White Curry Roti","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":380,"protein":22,"carbs":36,"fats":14,"fiber":5,"sodium":170,"potassium":370,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Egg Whites,Onion,Tomato,Whole Wheat Roti","health_benefits":"Very high lean protein. Low fat preparation supports weight management."},
{"name":"Chana Masala Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":460,"protein":16,"carbs":58,"fats":14,"fiber":10,"sodium":180,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chickpeas,Onion,Tomato,Whole Wheat Roti","health_benefits":"Chickpeas reduce LDL cholesterol. Very high fiber and potassium support BP management."},
{"name":"Lobia Curry Brown Rice","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":440,"protein":15,"carbs":62,"fats":10,"fiber":9,"sodium":150,"potassium":540,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Black Eyed Peas,Brown Rice,Onion,Tomato","health_benefits":"Black-eyed peas are very high in potassium and folate. Excellent for cardiovascular health."},
{"name":"Methi Sabzi Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":370,"protein":14,"carbs":46,"fats":9,"fiber":8,"sodium":110,"potassium":420,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fenugreek Leaves,Dal,Whole Wheat Roti","health_benefits":"Fenugreek helps lower blood sugar and cholesterol. Bitter compounds reduce inflammation."},
{"name":"Grilled Chicken Salad Bowl","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":350,"protein":30,"carbs":12,"fats":15,"fiber":5,"sodium":180,"potassium":560,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken Breast,Lettuce,Cucumber,Tomato,Lemon","health_benefits":"High protein low carb meal. Ideal for weight loss. Vegetables add potassium and antioxidants."},
{"name":"Moong Dal Khichdi","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":380,"protein":14,"carbs":52,"fats":8,"fiber":7,"sodium":120,"potassium":400,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moong Dal,Rice,Vegetables,Turmeric","health_benefits":"Easiest to digest complete meal. Moong dal is high in magnesium which relaxes blood vessels."},
{"name":"Tinda Sabzi Dal Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":350,"protein":12,"carbs":46,"fats":8,"fiber":7,"sodium":95,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Round Gourd,Dal,Whole Wheat Roti","health_benefits":"Tinda is high water content and low calorie. Mild on digestion and good for weight management."},
{"name":"Yam Curry Roti","category":"Lunch","meal_type":"Lunch","is_veg":True,"calories":390,"protein":10,"carbs":56,"fats":10,"fiber":8,"sodium":100,"potassium":510,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Yam,Onion,Tomato,Whole Wheat Roti","health_benefits":"Yam is rich in potassium and complex carbohydrates. Provides sustained energy with low BP impact."},
{"name":"Mackerel Curry Brown Rice","category":"Lunch","meal_type":"Lunch","is_veg":False,"calories":500,"protein":30,"carbs":46,"fats":20,"fiber":4,"sodium":210,"potassium":590,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Mackerel,Brown Rice,Onion,Tomato","health_benefits":"Mackerel is highest omega-3 fish. Regular consumption shown to reduce systolic BP significantly."},

# ── DINNER (30) ─────────────────────────────────────────────
{"name":"Roti Dal Salad","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":380,"protein":14,"carbs":48,"fats":9,"fiber":8,"sodium":120,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Whole Wheat Roti,Moong Dal,Cucumber,Tomato","health_benefits":"Light dinner ideal for BP patients. Moong dal is easy to digest at night."},
{"name":"Vegetable Khichdi","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":350,"protein":12,"carbs":50,"fats":8,"fiber":7,"sodium":110,"potassium":400,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rice,Moong Dal,Mixed Vegetables,Turmeric","health_benefits":"Complete digestible meal. Turmeric reduces inflammation. Perfect light dinner."},
{"name":"Grilled Fish Steamed Vegetables","category":"Dinner","meal_type":"Dinner","is_veg":False,"calories":340,"protein":32,"carbs":12,"fats":16,"fiber":5,"sodium":170,"potassium":620,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fish,Broccoli,Carrot,Lemon,Olive Oil","health_benefits":"Omega-3 rich fish. Steamed vegetables retain all potassium. Ideal BP-lowering dinner."},
{"name":"Lauki Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":350,"protein":12,"carbs":46,"fats":8,"fiber":8,"sodium":100,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bottle Gourd,Moong Dal,Whole Wheat Roti","health_benefits":"Lauki is one of the best BP-lowering vegetables. Light dinner that does not raise BP overnight."},
{"name":"Vegetable Soup Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":300,"protein":10,"carbs":38,"fats":8,"fiber":8,"sodium":130,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Carrot,Beans,Peas,Tomato,Whole Wheat Roti","health_benefits":"Warm soup before bed is calming. High vegetable content provides potassium and antioxidants."},
{"name":"Chicken Soup Light","category":"Dinner","meal_type":"Dinner","is_veg":False,"calories":280,"protein":24,"carbs":10,"fats":12,"fiber":2,"sodium":180,"potassium":480,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken,Garlic,Ginger,Pepper,Vegetables","health_benefits":"Garlic in soup provides allicin for BP reduction. Light and warming without calorie load."},
{"name":"Tofu Stir Fry Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":360,"protein":18,"carbs":36,"fats":16,"fiber":6,"sodium":130,"potassium":390,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tofu,Broccoli,Capsicum,Whole Wheat Roti","health_benefits":"Plant protein with minimal sodium. Broccoli provides sulforaphane for heart protection."},
{"name":"Broccoli Soup","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":220,"protein":9,"carbs":18,"fats":10,"fiber":6,"sodium":110,"potassium":440,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Broccoli,Low Fat Milk,Garlic","health_benefits":"Broccoli is highest vegetable source of sulforaphane. Garlic provides allicin for BP reduction."},
{"name":"Cauliflower Rice Bowl","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":260,"protein":10,"carbs":18,"fats":14,"fiber":6,"sodium":100,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cauliflower,Vegetables,Minimal Oil","health_benefits":"Very low carb alternative to rice. High fiber and very low calorie — ideal for weight loss."},
{"name":"Karela Sabzi Dal Roti Dinner","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":310,"protein":10,"carbs":38,"fats":9,"fiber":7,"sodium":90,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bitter Gourd,Dal,Whole Wheat Roti","health_benefits":"Karela compounds work overnight to regulate blood sugar. Evening consumption most effective."},
{"name":"Spinach Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":370,"protein":14,"carbs":46,"fats":9,"fiber":9,"sodium":120,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Spinach,Masoor Dal,Whole Wheat Roti","health_benefits":"Spinach nitrates convert to nitric oxide which relaxes blood vessels and lowers BP."},
{"name":"Moong Soup","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":220,"protein":12,"carbs":28,"fats":5,"fiber":8,"sodium":80,"potassium":420,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Whole Moong,Garlic,Ginger,Cumin","health_benefits":"Warm moong soup is highly digestible. Garlic and ginger boost circulation before sleep."},
{"name":"Ragi Roti Sabzi","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":310,"protein":9,"carbs":42,"fats":7,"fiber":8,"sodium":70,"potassium":360,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ragi Flour,Seasonal Vegetables,Minimal Oil","health_benefits":"Ragi is calcium-rich for vessel health. Low glycemic keeps BP stable overnight."},
{"name":"Mixed Veg Curry Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":360,"protein":10,"carbs":46,"fats":14,"fiber":7,"sodium":130,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Seasonal Vegetables,Onion,Tomato,Whole Wheat Roti","health_benefits":"Variety of vegetables ensures broad spectrum of BP-supporting minerals."},
{"name":"Snake Gourd Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":310,"protein":10,"carbs":40,"fats":7,"fiber":7,"sodium":90,"potassium":390,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Snake Gourd,Dal,Whole Wheat Roti","health_benefits":"Snake gourd is 95% water and diuretic — helps reduce fluid retention which lowers BP."},
{"name":"Chicken Lettuce Wrap","category":"Dinner","meal_type":"Dinner","is_veg":False,"calories":300,"protein":28,"carbs":8,"fats":16,"fiber":2,"sodium":180,"potassium":470,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken Breast,Lettuce,Onion,Lemon","health_benefits":"Very low carb high protein dinner. Supports muscle maintenance during weight loss."},
{"name":"Amaranth Leaves Sabzi Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":290,"protein":9,"carbs":36,"fats":7,"fiber":7,"sodium":80,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Amaranth Leaves,Garlic,Whole Wheat Roti","health_benefits":"Amaranth leaves have highest potassium among leafy greens. Excellent for evening BP management."},
{"name":"Tomato Garlic Soup Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":250,"protein":7,"carbs":32,"fats":8,"fiber":5,"sodium":110,"potassium":420,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tomato,Garlic,Onion,Whole Wheat Roti","health_benefits":"Garlic soup provides concentrated allicin for BP reduction. Tomato lycopene protects heart vessels."},
{"name":"Sardine Steamed Rice","category":"Dinner","meal_type":"Dinner","is_veg":False,"calories":420,"protein":30,"carbs":38,"fats":16,"fiber":3,"sodium":200,"potassium":560,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Sardine,Brown Rice,Lemon","health_benefits":"Sardines are richest source of EPA omega-3. Very affordable and highly BP-protective."},
{"name":"Lobia Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":380,"protein":14,"carbs":50,"fats":8,"fiber":9,"sodium":120,"potassium":530,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Black Eyed Peas,Whole Wheat Roti,Garlic","health_benefits":"Black-eyed peas provide very high potassium intake ideal for BP reduction."},
{"name":"Mushroom Garlic Soup","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":200,"protein":8,"carbs":14,"fats":10,"fiber":3,"sodium":100,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mushroom,Garlic,Onion,Low Fat Milk","health_benefits":"Very light dinner. Mushrooms and garlic both contain BP-lowering compounds."},
{"name":"Bathua Saag Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":300,"protein":10,"carbs":38,"fats":7,"fiber":8,"sodium":80,"potassium":500,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bathua Leaves,Dal,Whole Wheat Roti","health_benefits":"Bathua is very high in potassium and iron. Traditional winter green with strong heart benefits."},
{"name":"Ash Gourd Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":290,"protein":9,"carbs":36,"fats":7,"fiber":6,"sodium":85,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ash Gourd,Dal,Whole Wheat Roti","health_benefits":"Ash gourd is cooling and diuretic. Helps reduce water retention and supports BP reduction."},
{"name":"Low Fat Paneer Bhurji Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":360,"protein":20,"carbs":28,"fats":18,"fiber":4,"sodium":150,"potassium":330,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Low Fat Paneer,Onion,Tomato,Whole Wheat Roti","health_benefits":"High protein dinner reduces overnight hunger. Low fat paneer is calcium-rich for vessel health."},
{"name":"Barley Vegetable Soup","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":240,"protein":8,"carbs":36,"fats":5,"fiber":9,"sodium":110,"potassium":390,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Barley,Carrot,Beans,Celery,Onion","health_benefits":"Beta-glucan in barley lowers cholesterol overnight. Very filling and low calorie."},
{"name":"Prawn Stir Fry Light","category":"Dinner","meal_type":"Dinner","is_veg":False,"calories":320,"protein":28,"carbs":10,"fats":16,"fiber":2,"sodium":210,"potassium":440,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Prawns,Garlic,Vegetables,Minimal Oil","health_benefits":"Prawns are high protein low fat. Astaxanthin in prawns is powerful antioxidant for heart."},
{"name":"Turai Sabzi Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":300,"protein":8,"carbs":38,"fats":8,"fiber":7,"sodium":85,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ridge Gourd,Onion,Whole Wheat Roti","health_benefits":"Ridge gourd is high water content and very low calorie. Excellent for evening meal for weight loss."},
{"name":"Drumstick Sabzi Dal Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":340,"protein":12,"carbs":44,"fats":9,"fiber":9,"sodium":100,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Drumstick,Dal,Whole Wheat Roti","health_benefits":"Drumstick moringa pods are rich in vitamins C and K. Support BP reduction and bone health."},
{"name":"Egg Curry Roti Light","category":"Dinner","meal_type":"Dinner","is_veg":False,"calories":360,"protein":22,"carbs":34,"fats":12,"fiber":5,"sodium":170,"potassium":360,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Eggs,Onion,Tomato,Whole Wheat Roti","health_benefits":"Eggs provide complete protein and B vitamins. Light curry preparation keeps sodium controlled."},
{"name":"Palak Tofu Roti","category":"Dinner","meal_type":"Dinner","is_veg":True,"calories":340,"protein":16,"carbs":30,"fats":16,"fiber":7,"sodium":130,"potassium":500,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Spinach,Tofu,Whole Wheat Roti","health_benefits":"Spinach nitrates and tofu isoflavones both independently lower BP. Powerful combination."},

# ── SNACKS (30) ──────────────────────────────────────────────
{"name":"Roasted Chana","category":"Snack","meal_type":"Snack","is_veg":True,"calories":160,"protein":8,"carbs":20,"fats":4,"fiber":7,"sodium":20,"potassium":290,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chana,Cumin,Pepper","health_benefits":"High fiber and plant protein. Very low sodium. Keeps you full and stabilizes blood sugar."},
{"name":"Fruit Salad Bowl","category":"Snack","meal_type":"Snack","is_veg":True,"calories":180,"protein":3,"carbs":36,"fats":2,"fiber":6,"sodium":10,"potassium":480,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Apple,Banana,Papaya,Pomegranate,Guava","health_benefits":"Natural potassium from mixed fruits. Pomegranate punicalagin directly lowers BP."},
{"name":"Mixed Unsalted Nuts","category":"Snack","meal_type":"Snack","is_veg":True,"calories":220,"protein":7,"carbs":10,"fats":18,"fiber":4,"sodium":5,"potassium":320,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Unsalted Almonds,Walnuts,Cashews","health_benefits":"Magnesium from nuts relaxes blood vessels. Omega-3 from walnuts reduces inflammation."},
{"name":"Banana With Almond Butter","category":"Snack","meal_type":"Snack","is_veg":True,"calories":230,"protein":6,"carbs":28,"fats":12,"fiber":4,"sodium":10,"potassium":450,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Banana,Almond Butter","health_benefits":"High potassium from banana with healthy fats from almond butter provides sustained energy."},
{"name":"Makhana Roasted","category":"Snack","meal_type":"Snack","is_veg":True,"calories":140,"protein":5,"carbs":18,"fats":4,"fiber":3,"sodium":15,"potassium":210,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Makhana,Minimal Ghee,Pepper","health_benefits":"Fox nuts are low calorie and low sodium. Rich in magnesium and calcium for BP support."},
{"name":"Cucumber Carrot Hummus","category":"Snack","meal_type":"Snack","is_veg":True,"calories":200,"protein":7,"carbs":20,"fats":10,"fiber":6,"sodium":120,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cucumber,Carrot,Hummus","health_benefits":"Raw vegetables retain full potassium. Hummus provides plant protein and healthy fats."},
{"name":"Curd Pomegranate Bowl","category":"Snack","meal_type":"Snack","is_veg":True,"calories":170,"protein":8,"carbs":22,"fats":4,"fiber":3,"sodium":70,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Low Fat Curd,Pomegranate","health_benefits":"Probiotics from curd improve gut microbiome. Pomegranate punicalagin lowers BP significantly."},
{"name":"Apple With Walnut","category":"Snack","meal_type":"Snack","is_veg":True,"calories":190,"protein":4,"carbs":26,"fats":9,"fiber":5,"sodium":5,"potassium":350,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Apple,Walnuts","health_benefits":"Apple quercetin with walnut omega-3 provides powerful cardiovascular protection."},
{"name":"Sprouts Chaat No Salt","category":"Snack","meal_type":"Snack","is_veg":True,"calories":180,"protein":12,"carbs":22,"fats":4,"fiber":7,"sodium":15,"potassium":460,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mixed Sprouts,Onion,Tomato,Lemon,Cumin","health_benefits":"Raw sprouts are richest in bioavailable potassium. No-salt preparation ideal for BP patients."},
{"name":"Boiled Corn No Butter","category":"Snack","meal_type":"Snack","is_veg":True,"calories":130,"protein":4,"carbs":26,"fats":2,"fiber":4,"sodium":5,"potassium":240,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Corn,Lemon,Pepper","health_benefits":"Corn contains L-tryptophan which helps reduce stress and secondary BP elevation."},
{"name":"Greek Yogurt Bowl","category":"Snack","meal_type":"Snack","is_veg":True,"calories":190,"protein":14,"carbs":16,"fats":5,"fiber":3,"sodium":60,"potassium":330,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Greek Yogurt,Banana,Chia Seeds","health_benefits":"Very high protein keeps you full. Probiotics improve gut health which is linked to BP control."},
{"name":"Dates Walnut Mix","category":"Snack","meal_type":"Snack","is_veg":True,"calories":200,"protein":4,"carbs":28,"fats":10,"fiber":5,"sodium":5,"potassium":370,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Dates,Walnuts","health_benefits":"Dates are very high in potassium. Combined with walnut omega-3 provides heart-protective snack."},
{"name":"Pumpkin Seeds Mix","category":"Snack","meal_type":"Snack","is_veg":True,"calories":180,"protein":8,"carbs":8,"fats":14,"fiber":3,"sodium":5,"potassium":280,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Pumpkin Seeds,Sunflower Seeds","health_benefits":"Pumpkin seeds are highest source of magnesium among snacks. Directly relaxes blood vessels."},
{"name":"Amla With Honey","category":"Snack","meal_type":"Snack","is_veg":True,"calories":80,"protein":1,"carbs":16,"fats":1,"fiber":3,"sodium":5,"potassium":190,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Amla,Honey","health_benefits":"Amla is highest vitamin C source. Polyphenols prevent oxidation of LDL cholesterol."},
{"name":"Anjeer Dried Figs","category":"Snack","meal_type":"Snack","is_veg":True,"calories":160,"protein":3,"carbs":30,"fats":2,"fiber":5,"sodium":5,"potassium":340,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Dried Figs","health_benefits":"Figs contain potassium and polyphenols. Anti-inflammatory and BP-supportive snack."},
{"name":"Dark Chocolate Almonds","category":"Snack","meal_type":"Snack","is_veg":True,"calories":210,"protein":5,"carbs":16,"fats":15,"fiber":4,"sodium":10,"potassium":310,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Dark Chocolate 85%,Almonds","health_benefits":"Dark chocolate flavanols improve arterial flexibility. 1-2 squares daily shown to lower BP."},
{"name":"Boiled Sweet Potato","category":"Snack","meal_type":"Snack","is_veg":True,"calories":150,"protein":3,"carbs":30,"fats":1,"fiber":4,"sodium":10,"potassium":440,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Sweet Potato,Lemon,Cumin","health_benefits":"Sweet potato is very high in potassium. Naturally sweet so no sugar needed. Excellent BP snack."},
{"name":"Papaya Bowl","category":"Snack","meal_type":"Snack","is_veg":True,"calories":120,"protein":2,"carbs":24,"fats":1,"fiber":4,"sodium":8,"potassium":360,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Papaya,Lemon","health_benefits":"Papaya contains papain enzyme that improves digestion. Rich in potassium and antioxidants."},
{"name":"Guava With Pepper","category":"Snack","meal_type":"Snack","is_veg":True,"calories":100,"protein":2,"carbs":20,"fats":1,"fiber":6,"sodium":5,"potassium":400,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Guava,Black Pepper","health_benefits":"Guava is very high in potassium and lycopene. One of the best fruits for BP patients."},
{"name":"Watermelon Slice","category":"Snack","meal_type":"Snack","is_veg":True,"calories":90,"protein":2,"carbs":18,"fats":1,"fiber":2,"sodium":5,"potassium":320,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Watermelon","health_benefits":"L-citrulline in watermelon converts to arginine which opens blood vessels and lowers BP."},
{"name":"Pomegranate Seeds Bowl","category":"Snack","meal_type":"Snack","is_veg":True,"calories":130,"protein":2,"carbs":26,"fats":2,"fiber":4,"sodium":5,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Pomegranate","health_benefits":"Pomegranate has highest polyphenol content of any fruit. Punicalagin directly inhibits ACE enzyme to lower BP."},
{"name":"Jamun Indian Blackberry","category":"Snack","meal_type":"Snack","is_veg":True,"calories":80,"protein":1,"carbs":16,"fats":1,"fiber":3,"sodium":5,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Jamun","health_benefits":"Jamun is proven to lower blood sugar and supports BP management. Rich in anthocyanins."},
{"name":"Peanut Chikki Jaggery","category":"Snack","meal_type":"Snack","is_veg":True,"calories":200,"protein":6,"carbs":24,"fats":9,"fiber":2,"sodium":10,"potassium":220,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Peanuts,Jaggery","health_benefits":"Natural jaggery is less processed than sugar. Peanuts provide plant protein and heart-healthy fats."},
{"name":"Moong Dal Soup Snack","category":"Snack","meal_type":"Snack","is_veg":True,"calories":160,"protein":10,"carbs":20,"fats":3,"fiber":5,"sodium":60,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moong Dal,Garlic,Ginger,Cumin","health_benefits":"Warm protein-rich snack. Garlic provides allicin and ginger improves circulation."},
{"name":"Isabgol Psyllium Drink","category":"Snack","meal_type":"Snack","is_veg":True,"calories":30,"protein":0,"carbs":7,"fats":0,"fiber":5,"sodium":5,"potassium":30,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Psyllium Husk,Warm Water","health_benefits":"Psyllium husk is proven to lower both BP and cholesterol. Must drink immediately after mixing."},
{"name":"Roasted Pumpkin Seeds","category":"Snack","meal_type":"Snack","is_veg":True,"calories":160,"protein":8,"carbs":6,"fats":12,"fiber":2,"sodium":5,"potassium":280,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Pumpkin Seeds,Minimal Oil","health_benefits":"Highest magnesium content of any seed. One of the best BP-lowering snacks available."},
{"name":"Banana Oat Energy Balls","category":"Snack","meal_type":"Snack","is_veg":True,"calories":180,"protein":5,"carbs":28,"fats":6,"fiber":4,"sodium":15,"potassium":360,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Banana,Ground Flaxseeds","health_benefits":"Combined potassium from banana and omega-3 from flaxseeds provide excellent BP support."},
{"name":"Flaxseed Chikki","category":"Snack","meal_type":"Snack","is_veg":True,"calories":190,"protein":6,"carbs":22,"fats":9,"fiber":5,"sodium":5,"potassium":250,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Flaxseeds,Jaggery","health_benefits":"Flaxseed lignans lower BP by improving arterial flexibility. Rich in omega-3 and fiber."},
{"name":"Orange Segments","category":"Snack","meal_type":"Snack","is_veg":True,"calories":80,"protein":2,"carbs":16,"fats":1,"fiber":3,"sodium":5,"potassium":320,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Orange","health_benefits":"High vitamin C protects blood vessel walls. Hesperidin flavonoid in orange peel specifically lowers BP."},
{"name":"Chia Seed Water","category":"Snack","meal_type":"Snack","is_veg":True,"calories":70,"protein":3,"carbs":6,"fats":3,"fiber":4,"sodium":10,"potassium":80,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chia Seeds,Water,Lemon","health_benefits":"Chia seeds expand in stomach reducing hunger. Omega-3 from chia supports cardiovascular health."},

# ── MORNING DRINKS (25) ─────────────────────────────────────
{"name":"Warm Lemon Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":12,"protein":0,"carbs":3,"fats":0,"fiber":0,"sodium":5,"potassium":80,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Lemon,Warm Water","health_benefits":"Alkalizes body first thing. Vitamin C supports vascular health. Gentle diuretic helps reduce BP."},
{"name":"Raw Garlic Water Shot","category":"Morning","meal_type":"Morning","is_veg":True,"calories":8,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":2,"potassium":60,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Raw Garlic,Water","health_benefits":"Allicin from raw garlic is most potent natural BP-lowering compound. Most effective when consumed raw on empty stomach."},
{"name":"Lauki Juice","category":"Morning","meal_type":"Morning","is_veg":True,"calories":20,"protein":1,"carbs":4,"fats":0,"fiber":1,"sodium":8,"potassium":160,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bottle Gourd,Mint,Pepper","health_benefits":"Clinical studies show lauki juice lowers systolic BP. Diuretic effect reduces fluid retention."},
{"name":"Beetroot Juice","category":"Morning","meal_type":"Morning","is_veg":True,"calories":60,"protein":2,"carbs":12,"fats":0,"fiber":2,"sodium":50,"potassium":340,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Beetroot,Carrot,Ginger","health_benefits":"Dietary nitrates in beetroot convert to nitric oxide which dilates blood vessels. Can lower BP 4-10 mmHg within hours."},
{"name":"Amla Juice","category":"Morning","meal_type":"Morning","is_veg":True,"calories":30,"protein":0,"carbs":6,"fats":0,"fiber":1,"sodium":5,"potassium":190,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Amla,Water","health_benefits":"Highest vitamin C content of any food. Polyphenols prevent LDL oxidation and protect blood vessels."},
{"name":"Pomegranate Juice Fresh","category":"Morning","meal_type":"Morning","is_veg":True,"calories":80,"protein":1,"carbs":18,"fats":0,"fiber":1,"sodium":8,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Pomegranate","health_benefits":"Punicalagin inhibits ACE enzyme — same mechanism as BP medicines. Studies show significant BP reduction."},
{"name":"Green Tea","category":"Morning","meal_type":"Morning","is_veg":True,"calories":8,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":5,"potassium":40,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Green Tea Leaves,Water","health_benefits":"L-theanine and catechins in green tea improve arterial function. Anti-inflammatory and antioxidant."},
{"name":"Hibiscus Tea","category":"Morning","meal_type":"Morning","is_veg":True,"calories":6,"protein":0,"carbs":1,"fats":0,"fiber":0,"sodium":3,"potassium":30,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Dried Hibiscus Flowers,Water","health_benefits":"Clinical trials show hibiscus tea lowers systolic BP by 5-6 mmHg. Acts as natural ACE inhibitor."},
{"name":"Tulsi Ginger Tea","category":"Morning","meal_type":"Morning","is_veg":True,"calories":10,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":3,"potassium":40,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tulsi Leaves,Ginger,Water","health_benefits":"Tulsi reduces cortisol stress hormone that raises BP. Ginger reduces arterial stiffness."},
{"name":"Jeera Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":10,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":3,"potassium":40,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cumin Seeds,Water","health_benefits":"Cumin contains thymoquinone with anti-inflammatory properties. Supports digestive and cardiovascular health."},
{"name":"Fenugreek Seed Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":8,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":2,"potassium":35,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fenugreek Seeds,Water","health_benefits":"Fenugreek contains compounds that lower blood sugar and reduce LDL cholesterol. Overnight soaking maximizes benefits."},
{"name":"Coriander Seed Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":8,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":2,"potassium":40,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Coriander Seeds,Water","health_benefits":"Coriander seeds have mild diuretic effect helping reduce BP. Rich in potassium and anti-inflammatory compounds."},
{"name":"Cinnamon Detox Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":8,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":1,"potassium":25,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cinnamon Stick,Water","health_benefits":"Cinnamon helps stabilize blood sugar which indirectly supports BP control. Anti-inflammatory."},
{"name":"Ginger Lemon Tea","category":"Morning","meal_type":"Morning","is_veg":True,"calories":12,"protein":0,"carbs":3,"fats":0,"fiber":0,"sodium":3,"potassium":60,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ginger,Lemon,Water","health_benefits":"Ginger gingerols reduce arterial stiffness. Lemon provides vitamin C for vascular protection."},
{"name":"Cucumber Mint Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":6,"protein":0,"carbs":1,"fats":0,"fiber":0,"sodium":3,"potassium":50,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cucumber,Mint,Water","health_benefits":"Cucumber silica supports vascular health. Mint has mild antispasmodic effect on blood vessels."},
{"name":"Coconut Water Fresh","category":"Morning","meal_type":"Morning","is_veg":True,"calories":46,"protein":2,"carbs":9,"fats":0,"fiber":0,"sodium":25,"potassium":600,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fresh Coconut Water","health_benefits":"Highest natural source of potassium. Studies show regular coconut water consumption significantly lowers BP."},
{"name":"Turmeric Warm Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":10,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":2,"potassium":30,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Turmeric,Warm Water,Lemon","health_benefits":"Curcumin in turmeric is powerful anti-inflammatory. Reduces oxidative stress which damages blood vessels."},
{"name":"Apple Cider Vinegar Drink","category":"Morning","meal_type":"Morning","is_veg":True,"calories":15,"protein":0,"carbs":3,"fats":0,"fiber":0,"sodium":5,"potassium":60,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Apple Cider Vinegar,Water,Lemon","health_benefits":"Acetic acid in ACV improves insulin sensitivity and may lower BP over time."},
{"name":"Barley Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":40,"protein":1,"carbs":8,"fats":0,"fiber":1,"sodium":5,"potassium":80,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Barley,Water,Lemon","health_benefits":"Beta-glucan dissolves in water. Regular consumption lowers cholesterol and supports BP management."},
{"name":"Kokum Sherbet No Sugar No Salt","category":"Morning","meal_type":"Morning","is_veg":True,"calories":25,"protein":0,"carbs":5,"fats":0,"fiber":0,"sodium":3,"potassium":70,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Kokum,Water,Mint","health_benefits":"Kokum is cooling and anti-inflammatory. Hydroxy citric acid supports weight management."},
{"name":"Warm Turmeric Milk","category":"Morning","meal_type":"Morning","is_veg":True,"calories":120,"protein":6,"carbs":10,"fats":6,"fiber":0,"sodium":80,"potassium":280,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Low Fat Milk,Turmeric,Cardamom","health_benefits":"Calcium from milk supports healthy blood vessel function. Curcumin reduces inflammation."},
{"name":"Flaxseed Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":20,"protein":1,"carbs":2,"fats":1,"fiber":2,"sodium":3,"potassium":50,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Ground Flaxseeds,Warm Water","health_benefits":"Flaxseed lignans and omega-3 lower BP. Must be ground to release benefits."},
{"name":"Moringa Powder Water","category":"Morning","meal_type":"Morning","is_veg":True,"calories":15,"protein":1,"carbs":2,"fats":0,"fiber":1,"sodium":5,"potassium":90,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moringa Powder,Water","health_benefits":"Moringa contains isothiocyanates that directly inhibit compounds causing high BP. Most nutrient-dense supplement."},
{"name":"Cardamom Ginger Tea","category":"Morning","meal_type":"Morning","is_veg":True,"calories":10,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":2,"potassium":45,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cardamom,Ginger,Water","health_benefits":"Cardamom shown in studies to lower BP. Contains antioxidants that protect cardiovascular system."},
{"name":"Buttermilk No Salt","category":"Morning","meal_type":"Morning","is_veg":True,"calories":60,"protein":4,"carbs":6,"fats":2,"fiber":0,"sodium":50,"potassium":260,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Low Fat Curd,Water,Cumin,Mint","health_benefits":"Probiotic drink that improves gut microbiome linked to BP regulation. Calcium supports vascular function."},

# ── SALADS (15) ──────────────────────────────────────────────
{"name":"Raw Vegetable Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":80,"protein":3,"carbs":14,"fats":2,"fiber":5,"sodium":25,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cucumber,Tomato,Onion,Carrot,Lemon","health_benefits":"Raw vegetables retain maximum potassium. No cooking means no sodium added. Perfect BP salad."},
{"name":"Sprouts Chaat Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":180,"protein":12,"carbs":22,"fats":4,"fiber":7,"sodium":20,"potassium":460,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mixed Sprouts,Onion,Tomato,Lemon,Cumin","health_benefits":"Highest bioavailable potassium. Sprouts have increased enzyme activity after sprouting."},
{"name":"Beetroot Carrot Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":110,"protein":3,"carbs":22,"fats":2,"fiber":5,"sodium":60,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Beetroot,Carrot,Lemon,Mustard Seeds","health_benefits":"Beetroot nitrates dilate blood vessels. Carrots provide beta-carotene protecting heart vessels."},
{"name":"Kachumber Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":70,"protein":2,"carbs":12,"fats":2,"fiber":4,"sodium":20,"potassium":360,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cucumber,Tomato,Onion,Lemon,Coriander","health_benefits":"Classic Indian salad with zero added sodium. All ingredients high in potassium and antioxidants."},
{"name":"Spinach Tomato Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":90,"protein":4,"carbs":10,"fats":4,"fiber":5,"sodium":35,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Spinach,Tomato,Onion,Lemon,Olive Oil","health_benefits":"Spinach is highest potassium leafy green. Tomato lycopene protects arterial walls."},
{"name":"Pomegranate Cucumber Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":120,"protein":3,"carbs":24,"fats":2,"fiber":5,"sodium":10,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Pomegranate,Cucumber,Mint,Lemon","health_benefits":"Double BP benefit: pomegranate ACE inhibition plus cucumber diuretic effect."},
{"name":"Boiled Chickpea Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":220,"protein":10,"carbs":30,"fats":5,"fiber":8,"sodium":35,"potassium":480,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chickpeas,Onion,Tomato,Cucumber,Lemon","health_benefits":"Chickpeas are very high in potassium and fiber. Satisfying protein-rich salad for weight management."},
{"name":"Moong Sprout Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":160,"protein":10,"carbs":20,"fats":3,"fiber":6,"sodium":15,"potassium":420,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moong Sprouts,Tomato,Lemon,Ginger","health_benefits":"Sprouted moong has highest bioavailable magnesium. Excellent BP-supporting snack or side dish."},
{"name":"Grilled Chicken Salad","category":"Salad","meal_type":"Salad","is_veg":False,"calories":280,"protein":30,"carbs":10,"fats":12,"fiber":4,"sodium":180,"potassium":560,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken Breast,Lettuce,Cucumber,Tomato,Lemon","health_benefits":"High protein low carb. Potassium from vegetables counters any sodium in chicken."},
{"name":"Papaya Lime Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":100,"protein":2,"carbs":22,"fats":1,"fiber":4,"sodium":8,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Papaya,Lime,Mint","health_benefits":"Papain enzyme aids digestion. High potassium and antioxidant content."},
{"name":"Capsicum Onion Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":80,"protein":2,"carbs":14,"fats":2,"fiber":4,"sodium":15,"potassium":350,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Capsicum,Onion,Tomato,Lemon","health_benefits":"Capsicum is highest vegetable source of vitamin C. Onion quercetin specifically reduces BP."},
{"name":"Watermelon Mint Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":90,"protein":2,"carbs":20,"fats":1,"fiber":2,"sodium":5,"potassium":330,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Watermelon,Mint,Lime","health_benefits":"L-citrulline in watermelon is most effective natural compound for opening blood vessels."},
{"name":"Avocado Tomato Salad","category":"Salad","meal_type":"Salad","is_veg":True,"calories":200,"protein":4,"carbs":12,"fats":16,"fiber":8,"sodium":15,"potassium":600,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Avocado,Tomato,Onion,Lemon","health_benefits":"Avocado has highest potassium of any fruit. Heart-healthy fats combined with lycopene provide strong cardiovascular protection."},
{"name":"Tuna Salad No Mayo","category":"Salad","meal_type":"Salad","is_veg":False,"calories":260,"protein":32,"carbs":6,"fats":10,"fiber":2,"sodium":190,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tuna,Lettuce,Cucumber,Lemon","health_benefits":"Tuna omega-3 reduces inflammation. High protein low calorie meal. No-mayo preparation keeps sodium controlled."},
{"name":"Boiled Egg Vegetable Salad","category":"Salad","meal_type":"Salad","is_veg":False,"calories":220,"protein":14,"carbs":14,"fats":10,"fiber":4,"sodium":140,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Boiled Eggs,Cucumber,Tomato,Lettuce,Lemon","health_benefits":"Complete protein from eggs with potassium from vegetables. Balanced macro salad for weight management."},

# ── SOUPS (15) ──────────────────────────────────────────────
{"name":"Tomato Garlic Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":120,"protein":4,"carbs":18,"fats":5,"fiber":4,"sodium":100,"potassium":440,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tomato,Garlic,Onion,Olive Oil","health_benefits":"Garlic allicin and tomato lycopene together provide powerful cardiovascular protection."},
{"name":"Spinach Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":110,"protein":5,"carbs":12,"fats":5,"fiber":4,"sodium":90,"potassium":530,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Spinach,Garlic,Onion,Low Fat Milk","health_benefits":"Spinach nitrates dilate blood vessels. Highest potassium content of any soup base."},
{"name":"Moong Dal Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":160,"protein":10,"carbs":20,"fats":4,"fiber":5,"sodium":70,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moong Dal,Garlic,Ginger,Turmeric,Cumin","health_benefits":"Magnesium-rich moong with anti-inflammatory spices. Most digestible and BP-friendly soup."},
{"name":"Vegetable Clear Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":80,"protein":3,"carbs":12,"fats":2,"fiber":4,"sodium":90,"potassium":390,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Carrot,Beans,Peas,Celery,Pepper","health_benefits":"Nutrient-dense low calorie soup. All vegetables provide potassium and antioxidants."},
{"name":"Broccoli Almond Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":160,"protein":8,"carbs":14,"fats":9,"fiber":5,"sodium":90,"potassium":450,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Broccoli,Almonds,Low Fat Milk,Garlic","health_benefits":"Sulforaphane from broccoli and magnesium from almonds both protect cardiovascular system."},
{"name":"Chicken Clear Soup","category":"Soup","meal_type":"Soup","is_veg":False,"calories":160,"protein":18,"carbs":6,"fats":7,"fiber":1,"sodium":150,"potassium":410,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken,Garlic,Ginger,Pepper,Vegetables","health_benefits":"High protein warming soup. Garlic and ginger boost circulation. Collagen from bone broth supports vascular health."},
{"name":"Lentil Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":200,"protein":12,"carbs":26,"fats":5,"fiber":7,"sodium":90,"potassium":470,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Masoor Dal,Tomato,Garlic,Cumin","health_benefits":"Red lentils are high in folate. Folate reduces homocysteine which damages blood vessels."},
{"name":"Lauki Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":80,"protein":2,"carbs":12,"fats":3,"fiber":3,"sodium":50,"potassium":300,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Bottle Gourd,Garlic,Cumin,Pepper","health_benefits":"Lauki soup is diuretic and cooling. Very low calorie and actively lowers BP."},
{"name":"Carrot Ginger Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":100,"protein":3,"carbs":18,"fats":3,"fiber":4,"sodium":70,"potassium":390,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Carrot,Ginger,Onion,Minimal Oil","health_benefits":"Beta-carotene in carrot converts to vitamin A protecting blood vessel walls. Ginger improves circulation."},
{"name":"Beetroot Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":110,"protein":3,"carbs":20,"fats":3,"fiber":4,"sodium":80,"potassium":450,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Beetroot,Garlic,Onion,Lemon","health_benefits":"Beetroot nitrates convert to nitric oxide which dilates blood vessels. Can lower BP within 2-3 hours."},
{"name":"Barley Vegetable Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":200,"protein":7,"carbs":34,"fats":4,"fiber":8,"sodium":100,"potassium":400,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Barley,Carrot,Beans,Celery,Onion","health_benefits":"Beta-glucan in barley directly lowers cholesterol. High fiber keeps you full and manages BP."},
{"name":"Mushroom Garlic Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":130,"protein":6,"carbs":12,"fats":7,"fiber":3,"sodium":90,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mushroom,Garlic,Onion,Low Fat Milk","health_benefits":"Mushrooms contain eritadenine which lowers cholesterol. Garlic provides concentrated allicin."},
{"name":"Fish Pepper Soup","category":"Soup","meal_type":"Soup","is_veg":False,"calories":180,"protein":22,"carbs":6,"fats":8,"fiber":1,"sodium":160,"potassium":450,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fish,Pepper,Garlic,Ginger,Coriander","health_benefits":"Fish omega-3 and black pepper piperine improve nutrient absorption. High protein low calorie soup."},
{"name":"Moringa Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":90,"protein":4,"carbs":10,"fats":4,"fiber":4,"sodium":60,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Drumstick Leaves,Garlic,Onion,Tomato","health_benefits":"Moringa is most nutrient-dense food. Contains isothiocyanates that directly inhibit compounds causing high BP."},
{"name":"Cabbage Fat Burner Soup","category":"Soup","meal_type":"Soup","is_veg":True,"calories":70,"protein":3,"carbs":10,"fats":2,"fiber":4,"sodium":60,"potassium":340,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cabbage,Carrot,Beans,Onion,Tomato","health_benefits":"Very low calorie high volume soup. Cabbage glucosinolates have anti-inflammatory cardiovascular benefit."},

# ── BP SPECIALS (15) ──────────────────────────────────────────
{"name":"Raw Garlic Honey Shot","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":30,"protein":0,"carbs":7,"fats":0,"fiber":0,"sodium":2,"potassium":55,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Raw Garlic,Honey,Warm Water","health_benefits":"Most powerful natural BP remedy. Allicin with honey increases bioavailability. Take daily on empty stomach."},
{"name":"Beetroot Pomegranate Juice","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":90,"protein":2,"carbs":20,"fats":0,"fiber":3,"sodium":50,"potassium":510,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Beetroot,Pomegranate","health_benefits":"Dual action: beetroot nitrates dilate vessels AND pomegranate inhibits ACE enzyme. Most powerful BP drink combination."},
{"name":"Amla Aloe Vera Shot","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":20,"protein":0,"carbs":4,"fats":0,"fiber":1,"sodium":5,"potassium":110,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Amla,Aloe Vera Juice,Water","health_benefits":"Amla vitamin C with aloe vera acemannan provide powerful antioxidant and anti-inflammatory benefit for BP."},
{"name":"Flaxseed Walnut Mix","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":200,"protein":6,"carbs":6,"fats":17,"fiber":4,"sodium":3,"potassium":230,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Ground Flaxseeds,Walnuts","health_benefits":"Highest concentration of plant omega-3 ALA. Flaxseed lignans and walnut omega-3 together lower BP significantly."},
{"name":"Garlic Ginger Lemon Shot","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":15,"protein":0,"carbs":4,"fats":0,"fiber":0,"sodium":3,"potassium":80,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Garlic,Ginger,Lemon,Water","health_benefits":"Triple action: garlic allicin opens vessels, ginger reduces stiffness, lemon provides vascular-protecting vitamin C."},
{"name":"Celery Cucumber Juice","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":30,"protein":1,"carbs":6,"fats":0,"fiber":2,"sodium":40,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Celery,Cucumber,Mint,Lemon","health_benefits":"Phthalides in celery relax artery muscle walls — mechanism similar to calcium channel blockers (like Amlodipine)."},
{"name":"Hibiscus Pomegranate Tea","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":20,"protein":0,"carbs":4,"fats":0,"fiber":0,"sodium":3,"potassium":60,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Hibiscus Flowers,Pomegranate Juice","health_benefits":"Double ACE inhibition from hibiscus and pomegranate. Clinically shown to lower systolic BP 8-10 mmHg."},
{"name":"Moringa Amla Drink","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":25,"protein":1,"carbs":5,"fats":0,"fiber":1,"sodium":5,"potassium":150,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moringa Powder,Amla Juice,Water","health_benefits":"Moringa isothiocyanates with amla polyphenols provide comprehensive vascular protection."},
{"name":"Watermelon Ginger Juice","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":60,"protein":1,"carbs":14,"fats":0,"fiber":1,"sodium":5,"potassium":320,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Watermelon,Ginger,Lime","health_benefits":"L-citrulline from watermelon converted to arginine which directly opens blood vessels."},
{"name":"Fenugreek Coriander Water","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":10,"protein":0,"carbs":2,"fats":0,"fiber":0,"sodium":2,"potassium":50,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fenugreek Seeds,Coriander Seeds,Water","health_benefits":"Combined overnight-soaked seed water. Fenugreek reduces LDL and coriander acts as diuretic to lower BP."},
{"name":"Coconut Water Lemon Drink","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":50,"protein":2,"carbs":10,"fats":0,"fiber":0,"sodium":25,"potassium":600,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Fresh Coconut Water,Lemon,Mint","health_benefits":"Highest natural potassium drink available. Regular use shown in studies to significantly lower BP."},
{"name":"Banana Flaxseed Smoothie","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":220,"protein":8,"carbs":32,"fats":8,"fiber":7,"sodium":55,"potassium":550,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Banana,Ground Flaxseeds,Low Fat Milk","health_benefits":"High potassium from banana plus omega-3 from flaxseeds in one drink. Powerful daily BP supplement."},
{"name":"Turmeric Black Pepper Milk","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":120,"protein":6,"carbs":10,"fats":6,"fiber":0,"sodium":75,"potassium":280,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Low Fat Milk,Turmeric,Black Pepper,Cardamom","health_benefits":"Piperine in black pepper increases curcumin absorption 2000%. Anti-inflammatory and vascular protective."},
{"name":"Sesame Til Ladoo Small","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":120,"protein":3,"carbs":12,"fats":7,"fiber":2,"sodium":5,"potassium":110,"bp_friendly":True,"weight_loss_friendly":False,"ingredients":"Sesame Seeds,Jaggery","health_benefits":"Sesamin and sesamolin in sesame seeds specifically lower BP by inhibiting angiotensin-converting enzyme."},
{"name":"Kokum Celery Cooler","category":"BP Special","meal_type":"BP Special","is_veg":True,"calories":20,"protein":0,"carbs":4,"fats":0,"fiber":1,"sodium":3,"potassium":130,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Kokum,Celery,Mint,Water","health_benefits":"Kokum hydroxy citric acid with celery phthalides provide combined cooling and BP-reducing effect."},

# ── HIGH PROTEIN / SPECIALS (15) ─────────────────────────────
{"name":"High Protein Chicken Bowl","category":"Special","meal_type":"Special","is_veg":False,"calories":480,"protein":42,"carbs":28,"fats":18,"fiber":5,"sodium":200,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken Breast,Brown Rice,Broccoli","health_benefits":"42g protein in one meal. Supports muscle maintenance during weight loss. Broccoli adds cardiovascular protection."},
{"name":"Tofu Protein Bowl","category":"Special","meal_type":"Special","is_veg":True,"calories":390,"protein":30,"carbs":24,"fats":16,"fiber":8,"sodium":130,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Tofu,Rajma,Mixed Vegetables","health_benefits":"Plant-based complete protein. Soya isoflavones and rajma potassium together provide excellent BP support."},
{"name":"Soya Protein Salad","category":"Special","meal_type":"Special","is_veg":True,"calories":260,"protein":26,"carbs":16,"fats":8,"fiber":6,"sodium":90,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Soya Chunks,Vegetables,Lemon","health_benefits":"Highest plant protein. Soya chunks contain genistein which improves arterial elasticity."},
{"name":"Low Carb Paneer Bowl","category":"Special","meal_type":"Special","is_veg":True,"calories":340,"protein":24,"carbs":10,"fats":22,"fiber":4,"sodium":150,"potassium":310,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Low Fat Paneer,Vegetables,Spices","health_benefits":"High protein low carb meal. Calcium from paneer supports smooth muscle function in blood vessels."},
{"name":"Egg White Scramble","category":"Special","meal_type":"Special","is_veg":False,"calories":190,"protein":24,"carbs":4,"fats":6,"fiber":1,"sodium":110,"potassium":280,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Egg Whites,Spinach,Tomato,Turmeric","health_benefits":"Very high protein very low calorie. 24g protein per serving supports weight loss and muscle maintenance."},
{"name":"Greek Yogurt Protein Cup","category":"Special","meal_type":"Special","is_veg":True,"calories":210,"protein":18,"carbs":14,"fats":6,"fiber":2,"sodium":60,"potassium":370,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Greek Yogurt,Banana,Chia Seeds,Walnuts","health_benefits":"Probiotics improve gut microbiome linked to BP regulation. High protein and potassium combination."},
{"name":"Salmon Omega Bowl","category":"Special","meal_type":"Special","is_veg":False,"calories":420,"protein":34,"carbs":18,"fats":22,"fiber":4,"sodium":190,"potassium":640,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Salmon,Brown Rice,Broccoli,Lemon","health_benefits":"Most complete omega-3 meal. Salmon EPA and DHA shown to lower systolic BP by 4-5 mmHg in studies."},
{"name":"Sardine Protein Plate","category":"Special","meal_type":"Special","is_veg":False,"calories":320,"protein":30,"carbs":8,"fats":18,"fiber":2,"sodium":210,"potassium":490,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Sardine,Lemon,Salad Greens","health_benefits":"Sardines are most affordable omega-3 source. Calcium from sardine bones also supports BP control."},
{"name":"Moong Sprout High Protein Bowl","category":"Special","meal_type":"Special","is_veg":True,"calories":240,"protein":18,"carbs":26,"fats":5,"fiber":8,"sodium":40,"potassium":520,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Moong Sprouts,Quinoa,Vegetables,Lemon","health_benefits":"Complete plant protein with very high potassium. Highest bioavailable nutrients in one bowl."},
{"name":"Chicken Lettuce Wrap Special","category":"Special","meal_type":"Special","is_veg":False,"calories":280,"protein":32,"carbs":8,"fats":12,"fiber":3,"sodium":180,"potassium":470,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Chicken Breast,Lettuce,Onion,Lemon","health_benefits":"Zero refined carbs. High protein satiety meal. Ideal for people monitoring BP and managing weight."},
{"name":"Fat Burner Detox Bowl","category":"Special","meal_type":"Special","is_veg":True,"calories":160,"protein":6,"carbs":18,"fats":4,"fiber":6,"sodium":40,"potassium":430,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Cabbage,Carrot,Spinach,Lemon,Ginger","health_benefits":"Very low calorie high volume meal. Glucosinolates from cabbage and spinach nitrates together support BP and weight loss."},
{"name":"Protein Oats Flaxseed","category":"Special","meal_type":"Special","is_veg":True,"calories":300,"protein":20,"carbs":30,"fats":10,"fiber":9,"sodium":75,"potassium":380,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Oats,Whey,Ground Flaxseeds,Banana","health_benefits":"Triple action: oat beta-glucan, flaxseed omega-3, and whey protein together support weight loss and BP management."},
{"name":"Rajma Protein Bowl","category":"Special","meal_type":"Special","is_veg":True,"calories":360,"protein":18,"carbs":48,"fats":8,"fiber":12,"sodium":130,"potassium":560,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Rajma,Brown Rice,Onion,Garlic","health_benefits":"Rajma is highest potassium legume. Combined with garlic allicin provides one of the most effective BP-lowering meals."},
{"name":"Mackerel Omega Plate","category":"Special","meal_type":"Special","is_veg":False,"calories":380,"protein":30,"carbs":10,"fats":22,"fiber":2,"sodium":200,"potassium":570,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mackerel,Lemon,Steamed Vegetables","health_benefits":"Mackerel has highest EPA and DHA omega-3 among affordable fish. Regular consumption significantly lowers BP."},
{"name":"Low Cal Sprout Khichdi","category":"Special","meal_type":"Special","is_veg":True,"calories":320,"protein":16,"carbs":44,"fats":6,"fiber":9,"sodium":90,"potassium":510,"bp_friendly":True,"weight_loss_friendly":True,"ingredients":"Mixed Sprouts,Brown Rice,Moong Dal,Vegetables","health_benefits":"Complete nutrition in one bowl. Highest potassium from sprouted legumes combined with fiber-rich brown rice."},
]


# ============================================================
# COMPUTE SCORES & INSERT
# ============================================================

def compute_recipe_scores(recipe_data):
    """Compute health scores for a recipe dict."""
    sod = recipe_data.get("sodium", 0) or 0
    pot = recipe_data.get("potassium", 0) or 0
    pro = recipe_data.get("protein", 0) or 0
    fib = recipe_data.get("fiber", 0) or 0
    cal = recipe_data.get("calories", 0) or 0
    fat = recipe_data.get("fats", 0) or 0

    # BP Score
    bp_score = 0
    if sod < 150:  bp_score += 40
    elif sod < 300: bp_score += 20
    if pot > 400:   bp_score += 30
    elif pot > 200: bp_score += 15
    bp_score = min(100, bp_score + 30)  # base for bp_friendly items

    # Diabetes Score
    dia_score = 0
    if fib >= 7:  dia_score += 30
    elif fib >= 4: dia_score += 15
    if pro >= 15:  dia_score += 25
    dia_score = min(100, dia_score + 45)

    # Weight Loss Score
    wl_score = 0
    if cal < 300:  wl_score += 40
    elif cal < 450: wl_score += 20
    if pro >= 18:  wl_score += 25
    if fib >= 7:   wl_score += 20
    wl_score = min(100, wl_score + 15)

    # Nutrition Score
    nut_score = 0
    if pro >= 12:  nut_score += 25
    if fib >= 5:   nut_score += 25
    if sod < 400:  nut_score += 25
    if fat < 15:   nut_score += 15
    nut_score = min(100, nut_score + 10)

    return bp_score, dia_score, wl_score, nut_score


with app.app_context():

    print("=" * 60)
    print("SEEDING HEALTH CONDITIONS...")
    print("=" * 60)
    seed_health_conditions()
    print("✅ Health conditions seeded.")

    print("\n" + "=" * 60)
    print("SEEDING RECIPES...")
    print("=" * 60)

    # Clear existing
    Recipe.query.delete()
    db.session.commit()
    print("🗑️  Old recipes cleared.")

    inserted = 0
    for rd in recipes_data:
        bp_s, dia_s, wl_s, nut_s = compute_recipe_scores(rd)

        recipe = Recipe(
            name                 = rd["name"],
            category             = rd.get("category"),
            meal_type            = rd.get("meal_type"),
            is_veg               = rd.get("is_veg", True),
            calories             = rd.get("calories", 0),
            protein              = rd.get("protein", 0),
            carbs                = rd.get("carbs", 0),
            fats                 = rd.get("fats", 0),
            fiber                = rd.get("fiber", 0),
            sodium               = rd.get("sodium", 0),
            potassium            = rd.get("potassium", 0),
            bp_friendly          = rd.get("bp_friendly", True),
            diabetes_friendly    = rd.get("diabetes_friendly", True),
            weight_loss_friendly = rd.get("weight_loss_friendly", True),
            heart_friendly       = rd.get("heart_friendly", True),
            ingredients          = rd.get("ingredients", ""),
            health_benefits      = rd.get("health_benefits", ""),
            cooking_time         = rd.get("cooking_time", "20 mins"),
            difficulty           = rd.get("difficulty", "easy"),
            bp_score             = bp_s,
            diabetes_score       = dia_s,
            weight_loss_score    = wl_s,
            nutrition_score      = nut_s,
            # Auto-set flags
            high_protein  = (rd.get("protein", 0) or 0) >= 20,
            high_fiber    = (rd.get("fiber",   0) or 0) >= 7,
            low_sodium    = (rd.get("sodium",  0) or 0) < 400,
            
        )
        db.session.add(recipe)
        inserted += 1

    db.session.commit()

    # ── Summary ───────────────────────────────────────────────
    print(f"\n✅ Total recipes inserted: {inserted}")
    print("\n📊 Breakdown by category:")
    from collections import Counter
    cats = Counter(rd["category"] for rd in recipes_data)
    for cat, count in sorted(cats.items()):
        print(f"   {cat:<20} {count} recipes")

    bp_count  = sum(1 for rd in recipes_data if rd.get("bp_friendly"))
    wl_count  = sum(1 for rd in recipes_data if rd.get("weight_loss_friendly"))
    veg_count = sum(1 for rd in recipes_data if rd.get("is_veg"))

    print(f"\n   BP Friendly:         {bp_count}")
    print(f"   Weight Loss:         {wl_count}")
    print(f"   Vegetarian:          {veg_count}")
    print(f"   Non-Vegetarian:      {inserted - veg_count}")
    print("\n🎉 Seeding complete! Run: python app.py")
    print("=" * 60)