"""Initial migration

Revision ID: 4f75a68139a4
Revises: 
Create Date: 2026-06-27 17:08:29.905712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f75a68139a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthmetrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_healthmetrics_metrictype'))
        batch_op.drop_index(batch_op.f('ix_healthmetrics_recordedat'))
        batch_op.drop_index(batch_op.f('ix_healthmetrics_userid'))

    op.drop_table('healthmetrics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthmetrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metrictype', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('value1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recordedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name=op.f('healthmetrics_userid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('healthmetrics_pkey'))
    )
    with op.batch_alter_table('healthmetrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_healthmetrics_userid'), ['userid'], unique=False)
        batch_op.create_index(batch_op.f('ix_healthmetrics_recordedat'), ['recordedat'], unique=False)
        batch_op.create_index(batch_op.f('ix_healthmetrics_metrictype'), ['metrictype'], unique=False)

    # ### end Alembic commands ###
